{
 "title": "Logs",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": {}
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Number of Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({service_name=\"$container\",stream=~\"$stream\"})[$__interval])) by (stream)"
    }
   ]
  },
  {
   "title": "Number of Filtered Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"$container\",stream=~\"$stream\"} |~ `(?i)$search` [$__auto]))"
    }
   ]
  },
  {
   "title": "Live Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$container\", stream=~\"$stream\"} |~ \"(?i)$search\""
    }
   ]
  }
 ]
}